create or replace TABLE SWIGGY.LANDING.FOOD (
	F_ID VARCHAR(200),
	ITEM VARCHAR(200),
	VEG_OR_NON_VEG VARCHAR(200)
);


create or replace TABLE SWIGGY.LANDING.MENU (
	MENU_ID VARCHAR(200),
	R_ID NUMBER(38,0),
	F_ID VARCHAR(200),
	CUISINE VARCHAR(200),
	PRICE FLOAT
);


create or replace TABLE SWIGGY.LANDING.ORDERS (
	ORDER_DATE DATE,
	SALES_QTY NUMBER(38,0),
	SALES_AMOUNT FLOAT,
	CURRENCY VARCHAR(200),
	USER_ID NUMBER(38,0),
	R_ID FLOAT
);


create or replace TABLE SWIGGY.LANDING.RESTAURANT (
	ID NUMBER(38,0),
	NAME VARCHAR(200),
	CITY VARCHAR(200),
	RATING VARCHAR(200),
	RATING_COUNT VARCHAR(200),
	COST VARCHAR(200),
	CUISINE VARCHAR(200),
	LIC_NO VARCHAR(200),
	LINK VARCHAR(200),
	ADDRESS VARCHAR(200),
	MENU VARCHAR(200)
);


create or replace TABLE SWIGGY.LANDING.USERS (
	USER_ID NUMBER(38,0),
	NAME VARCHAR(200),
	EMAIL VARCHAR(200),
	PASSWORD VARCHAR(200),
	AGE NUMBER(38,0),
	GENDER VARCHAR(200),
	MARITAL_STATUS VARCHAR(200),
	OCCUPATION VARCHAR(200),
	MONTHLY_INCOME VARCHAR(200),
	EDUCATIONAL_QUALIFICATIONS VARCHAR(200),
	FAMILY_SIZE NUMBER(38,0)
);